CREATE DATABASE zoom;

CREATE TABLE account(
userID BIGINT PRIMARY KEY,
name VARCHAR(100) NOT NULL
);

CREATE TABLE room(
roomID BIGINT PRIMARY KEY,
roomName VARCHAR(50) NOT NULL
);

CREATE TABLE messages(
messageID BIGINT PRIMARY KEY,
userID BIGINT,
message VARCHAR(100) NOT NULL,
FOREIGN KEY(userID) REFERENCES account(userID),
FOREIGN KEY(roomID) REFERENCES room(roomID)
);

