CREATE DATABASE zoom;

CREATE TABLE "user" (
userID BIGSERIAL NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL
);


CREATE TABLE "room" (
roomID BIGSERIAL NOT NULL PRIMARY KEY,
roomName VARCHAR(50) NOT NULL,
);


CREATE TABLE "messages" (
messageID BIGSERIAL NOT NULL PRIMARY KEY,
userID BIGSERIAL,
message VARCHAR(100) NOT NULL,
CONSTRAINT fk_user
FOREIGN KEY(userID)
REFERENCES "user"(userID),
CONSTRAINT fk_room
FOREIGN KEY(roomID)
REFERENCES "room"(roomID)
);

