CREATE DATABASE zoom;

CREATE TABLE account(
id BIGINT PRIMARY KEY,
name VARCHAR(100) NOT NULL
);

CREATE TABLE room(
id BIGINT PRIMARY KEY,
name VARCHAR(50) NOT NULL
);

CREATE TABLE messages(
id BIGINT PRIMARY KEY,
userID BIGINT,
roomID BIGINT,
message VARCHAR(200) NOT NULL,
timeSent TIMESTAMP NOT NULL,
FOREIGN KEY(userID) REFERENCES account(id),
FOREIGN KEY(roomID) REFERENCES room(id)
);

